---
- name: Install nginx
  hosts: node1
  become: yes
      
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Start nginx
    service:
      name: nginx
      state: started
