---
- name: Install firewalld
  hosts: all
  become: yes
  tasks:
    - name: Install firewalld
      apt:
        name: firewalld
        state: present
    - name: Start firewalld
      service:
        name: firewalld
        state: started
    - name: Disable ufw
      service:
        name: ufw
        state: stopped
# PLAY 2: nginx on webserver
- hosts: webserver
  become: yes
  tasks:
    - name: Install nginx
      include_tasks: nginx_tasks.yaml   # in order to reuse code we can include
                                       # the tasks we have already written
    - name: open firewall port
      firewalld:
        service: http
        immediate: true
        permanent: true
        state: enabled
    - name: set content directory
      file:
        path: /var/www/html
        state: directory
        mode: u=rwx,g=rwx,o=rx,g+s
    - name: create default page content
      copy:
        content: "Welcome to {{ ansible_fqdn }} on {{ ansible_default_ipv4.address }}\n"
        dest: /var/www/html/index.html
        mode: u=rw,g=rw,o=r
# PLAY 3: MariaDB on dbserver
- hosts: dbserver
  become: yes
  tasks:
    - name: install MariaDB server
      apt:
        name: mariadb-server
        state: present
    - name: enable and start MariaDB server
      service:
        name: mariadb
        enabled: yes
        state: started
# PLAY 4: rsyslog on logserver
- hosts: logserver
  become: yes
  tasks:
    - name: configure rsyslog remote log reception over udp
      lineinfile:                       # a module to change a single line in a file
        path: /etc/rsyslog.conf
        line: "{{ item }}"
        state: present
      with_items:
        - '$ModLoad imudp'
        - '$UDPServerRun 514'
      notify:
        - restart rsyslogd
    - name: open firewall port
      firewalld:
        port: 514/udp
        immediate: true
        permanent: true
        state: enabled
  handlers:
    - name: restart rsyslogd
      service:
        name: rsyslog
        state: restarted
#PLAY 5: rsyslog config on webserver and dbserver    
- hosts: webserver:dbserver
  become: yes
  tasks:
    - name: configure rsyslog
      lineinfile:
        path: /etc/rsyslog.conf
        line: '*.* @172.16.97.217:514'
        state: present
      notify:
        - restart rsyslogd
  handlers:
    - name: restart rsyslogd
      service:
        name: rsyslog
        state: restarted
