# This is a basic workflow to help you get started with Actions

name: Deploy Ansible

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ansbile-playbook:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            ../ansible/playbook.yml
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.2.0
        with:
          # Ansible playbook filepath
          playbook: playbook.yml
          directory: ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory ../hosts.txt
