# This is a basic workflow to help you get started with Actions

name: Master Configuration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update and install packages
        run: |
          sudo apt-get update && sudo apt-get -y upgrade
          sudo apt-get install -y ansible
          sudo apt-get install -y ansible-lint
          sudo apt-get install -y sshpass
          sudo apt-get install -y docker
          sudo apt-get install -y docker.io
      - name: Setup Ansible
        run: |
          sudo cp ./hosts.txt /etc/ansible/hosts
          sudo cp ./ansible/servers /etc/ansible/group_vars/
      - name: Deploy public key
        run: |
          for host in `egrep -v '(^\[|^$)' hosts.txt`;  
          do  
            sshpass -p ${{secrets.HOST_PASSWORD}} ssh-copy-id netlab@$host -o StrictHostKeyChecking=no  
          done
